# The name of a collection in `src/collection_mapper.py` to restrict to
collection: null
# The path to a text file that has a newline separated list of dataset names to exclusively include.
dataset-names: "src/configs/common_pile_datasets.txt"
# Select one of ['commercial', 'unspecified', 'non-commercial', 'academic-only']
# Where `commercial` includes only commercially licensed datasets, `unspecified`
# includes commercially licensed or datasets without any found license, `non-commericial`
# includes commerically licensed, unspecified, and non-commerically licensed datasets.
# `academic-only` includes all datasets, even those with academic-only restrictions.
license_use: "academic-only"
# If 1, OpenAI generated data will be included even if license_use would have excluded it
openai-license-override: 0
# If 1, GitHub license information will be used if no information (‚undefined‘) is available for our Data Provenance source
dpi-undefined-license-override: 0
# 1 means datasets with attribution requirements are fine, 0 excludes them
license_attribution: 1
# 1 means datasets with share-alike requirements are fine, 0 excludes them
license_sharealike: 1
# 1 means allow any model generated content, 0 means do not allow model generated content
model-generated: 1
# To restrict the number of languages, specify keys or values from `constants/language_families.json`
languages: []
# To restrict the number of languages, specify keys or values from `constants/task_groups.json`
tasks: []
# To restrict the number of languages, specify keys or values from `constants/domain_groups.json`
domains: []
# Specific text sources to constrain our selection to (including no text sources). Points to a txt file of sources, or null.
text-sources: null
# Start time as `YYYY-MM-DD`. Excludes datasets created before this time
start-time: null
# End time as `YYYY-MM-DD`. Excludes datasets created after this time
end-time: null
data-limit: 0
output-format: "concat_dialog" # "messages" or "supervised" or "concat_dialog"
savedir: "data/"
# debug: True
