name: CI to test new collections

on:
  pull_request:
    paths:
      - 'data_summaries/**.json'  # Trip only when data summary changed/added

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Cache Python dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pip  # This path can vary depending on your OS and Python version
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install -U pip
        pip install -r requirements.txt

    - name: Identify Collections
      run: python .github/identify_collections_to_test.py

    - name: Run Tests
      run: |
        while IFS= read -r collection; do
          python src/test_new_collection.py --collection "$collection"
        done <<< "${{ steps.collection.outputs.collections }}"
